# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppleRate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppleRate
pod ‘Alamofire’
pod ‘ObjectMapper’
pod ‘Kingfisher’
pod ‘EasyPeasy’

  target 'AppleRateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppleRateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
