# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Share Contact by QR code' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  use_frameworks! 
  pod 'ImageRow' 
  pod 'Eureka'
  pod 'EasyPeasy'
  pod 'PostalAddressRow' 
  pod 'QRCode'
  pod 'NVActivityIndicatorView' 
  pod 'PhoneNumberKit'
  pod 'TwicketSegmentedControl' 

  # Pods for Share Contact by QR code

  target 'Share Contact by QR codeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Share Contact by QR codeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
