# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test

  target 'testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'Alamofire', '~> 4.4'
  pod ‘Kingfisher’
  pod ‘EasyPeasy’


end
